print('\tBILHETE\n')
print('\tSe tu me amas , ama -me baixinho')
print('\tNão o grites de cima dos telhados')
print('\tDeixa em paz os passarinhos')
print('\tDeixa em paz a mim!')
print('\tSe me queres,')
print('\tenfim,')
print('\ttem de ser bem devagarinho, Amada,')
print('\tque a vida é breve, e o amor mais breve ainda\n')
print('\tMario Quintana')
